### ISSUE TITLE
USER STORY: Signup and login 

### ISSUE THREAD

**Issue by RobinGJonsson** [RobinGJonsson/UnderDaC#15]
As a recurring customer I can register and login to the site so that my details are remembered the next time I order

## Tasks

- [x] Create signup and signing with Allauth template
- [x] Add first name, last name, and phone to the customer

**Comment by ghost** [comment]
hey , 
I think i could help with integration with FB/GOOGLE/APPLE

edit ; I'm a new programmer who was searching issues and would love to help for $0
